package pojo;
// Generated Oct 8, 2022 10:51:21 PM by Hibernate Tools 4.3.1

import DAO.DAOteacher;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblTcr generated by hbm2java
 */
@ManagedBean
public class TblTcr  implements java.io.Serializable {


     private Integer idTeacher;
     private String namaTeacher;
     private String gender;
     private String noTelp;
     private String address;
     private String gaji;

     
     
    public void save_teacher()
     {
         DAO.DAOteacher add = new DAOteacher();
         add.add_teacher(this);
     } 
     
     
    public List<TblTcr> getAllRecordstcr()
     {
         DAOteacher tea = new DAOteacher();
         List<TblTcr> ltea = tea.retrieveTblTcr();
         return ltea;
     }
    
    
    public String getByIdtcr()
    {
        String id_employee = idTeacher.toString();
        DAOteacher tea = new DAOteacher();
        List<TblTcr> ltea = tea.getbyID(id_employee);
        namaTeacher = ltea.get(0).getNamaTeacher();
        gender = ltea.get(0).getGender();
        noTelp = ltea.get(0).getNoTelp();
        gaji = ltea.get(0).getGaji();
        address = ltea.get(0).getAddress();
        return"teacher";
    }
    
    
    
    public String editteach(){
        DAOteacher tea = new DAOteacher();
        tea.editTcr(this);
        namaTeacher = "";
        gender = "";
        noTelp = "";
        gaji = "";
        address ="";
        return "teacher";
    }
    
    
    public String deleteteach(){
        DAOteacher tea = new DAOteacher();
        tea.deleteTcr(idTeacher);
        namaTeacher = "";
        gender = "";
        noTelp = "";
        gaji = "";
        address ="";
        return "teacher";
    }
    
    public String resetteach(){
        DAOteacher tea = new DAOteacher();
        tea.resetTcr(this);
        namaTeacher = "";
        gender = "";
        noTelp = "";
        gaji = "";
        address ="";
        return "teacher";
    }
    
    
    
    public TblTcr() {
    }

    public TblTcr(String namaTeacher, String gender, String noTelp, String address, String gaji) {
       this.namaTeacher = namaTeacher;
       this.gender = gender;
       this.noTelp = noTelp;
       this.address = address;
       this.gaji = gaji;
    }
   
    public Integer getIdTeacher() {
        return this.idTeacher;
    }
    
    public void setIdTeacher(Integer idTeacher) {
        this.idTeacher = idTeacher;
    }
    public String getNamaTeacher() {
        return this.namaTeacher;
    }
    
    public void setNamaTeacher(String namaTeacher) {
        this.namaTeacher = namaTeacher;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getGaji() {
        return this.gaji;
    }
    
    public void setGaji(String gaji) {
        this.gaji = gaji;
    }




}


