package pojo;
// Generated Oct 8, 2022 10:51:21 PM by Hibernate Tools 4.3.1


import DAO.DAOLogin;
import DAO.DAOuser;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     
     public void save_user(){
         DAOLogin add = new DAOLogin();
         add.add_user(this);
     }
          
     public String login_user()
     {
         DAOLogin uDao = new DAOLogin();
         List<TblUser> us = uDao.getBy(username, password);
         try{
            if(us != null){
                username = us.get(0).username;
                password = us.get(0).password;
                return "dashboard";
            }
         } catch (Exception e){
             System.out.println(e);
         }
         return "gagallogin";  
     }
     
    public List<TblUser> getAllRecords()
    {
        DAOuser usr = new DAOuser();
        List<TblUser> lUsr = usr.retrieveTblUser();
        return lUsr;
    }
     
     public String getById()
     {
         String id_user = idUser.toString();
         DAOuser usr = new DAOuser();
         List<TblUser> lUsr = usr.getByID(id_user);
         username = lUsr.get(0).username;
         password = lUsr.get(0).password;
         return "admin";
     }
     
    public String edit()
    {
        DAOuser usr = new DAOuser();
        usr.editUser(this);
        username = "";
        password = "";
        return "admin";
    }
     
    public String delete()
    {
     //   String id_user = idUser.toString();
        DAOuser usr = new DAOuser();
        usr.deleteUser(idUser);
        username = "";
        password = "";
        return "admin";
    }
     
    public String reset(){
        DAOuser usr = new DAOuser();
        usr.resetUser(this);
        username ="";
        password ="";
        return "admin";
    }
    
    public TblUser() {
    }

    public TblUser(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


